### ISSUE TITLE
Refund gas cost to bin/shelf creator

### ISSUE THREAD

**Issue by austinkline** [Flowtyio/lost-and-found#7]

**Comment by aishairzay** [comment]
Just to clarify is this issue about refunding the gas cost (cost to run the transaction), or for a way to retrieve the locked flow that was provided for storage reasons?
I'm assuming the latter

**Comment by austinkline** [comment]
The latter, correct. The hope for how I wrote much of this is that dapps pay for the storage but it should all be refunded to them once the storage they created is no longer in use.

This is already being done for tickets which are the resource that contain items to be redeemed, but it doesn't apply to the hierarchical resources that organize those tickets (Shelves and Bins)
